name: veil-build

on:
  push:
    branches:
      - main

jobs:
  build-job:
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '[ci skip]') == false
    name: ${{ matrix.name }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS (x64)
            os: macos-11
          - name: Windows (x64)
            os: windows-2019
            cmake_flags: -DCMAKE_CFLAGS=-static
          - name: Linux (x64)
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Ninja
        run: ${{ contains(matrix.os, 'macos') && 'brew install ninja' || contains(matrix.os, 'windows') && 'choco install ninja' || 'sudo apt-get install ninja-build' }}

      - name: Configure
        run: cmake -S . -B build/Debug -G Ninja -DCMAKE_BUILD_TYPE=Debug ${{ matrix.cmake_flags }}

      - name: Build
        run: cmake --build build/Debug -- -j `node -p 'os.cpus().length'`

      - name: Sanity Test
        run: ./build/Debug/veil --version
